const mainNav = [
   { url: '/react-inside', name: 'inside react', show: false},
   { url: '/react-outside', name: 'outside react', show: false},
   { url: '/html-css', name: 'HTML css', show: false},
   { url: '/javascript', name: 'JavaScript' , show: false},
];

const subs = [
   { url: '/react-inside/rendering', name: 'JSX', show: false},
   { url: '/react-inside/event', name: 'EVENT', show: false},
   { url: '/react-inside/state', name: 'State', show: false},
   { url: '/react-outside/ref', name: 'ref', show: false},
   { url: '/react-outside/effect', name: 'Effect', show: false},
   { url: '/html-css/html-basic', name: 'html', show: false},
   { url: '/html-css/css-tips', name: 'Tips', show: false},
   { url: '/html-css/css-attribute', name: 'Attributes', show: false},
   { url: '/html-css/form-basic', name: 'Form', show: false},
   { url: '/html-css/form-types', name: 'FormType ', show: false},
   { url: '/html-css/input-types', name: 'Input', show: false},
   { url: '/javascript/js', name: 'Basic', show: false},
   { url: '/javascript/object', name: 'Object', show: false},
   { url: '/javascript/async', name: 'Async', show: false},
];
const links = [
   { url: '/react-inside/rendering/jsx-markup', name: 'JSX', show: false},
   { url: '/react-inside/rendering/props-injection', name: 'Props', show: false},
   { url: '/react-inside/rendering/how-rendering', name: 'About Render', show: false},
   { url: '/react-inside/event/event-handle', name: 'Event handle', show: false},
   { url: '/react-inside/event/handle-state', name: 'useState', show: false},
   { url: '/react-inside/event/rendering-commit', name: 'Rendering', show: false},
   { url: '/react-inside/event/object-state-update', name: 'Object Handle', show: false},
   { url: '/react-inside/event/array-state-update', name: 'Array Handle', show: false},
   { url: '/react-inside/state/handle-useState', name: 'handle input', show: false},
   { url: '/react-inside/state/state-architecture', name: 'state 구조화', show: false},
   { url: '/react-inside/state/state-hoisting', name: 'state 공유', show: false},
   { url: '/react-inside/state/state-reducer', name: 'useReducer', show: false},
   { url: '/react-inside/state/context-prop-delivery', name: 'Context', show: false},
   { url: '/react-inside/state/context-useReducer', name: 'Context-useReducer', show: false},
   { url: '/react-outside/ref/using-ref', name: 'ref로 값 참조', show: false},
   { url: '/react-outside/ref/DOM-by-ref', name: 'Ref로 DOM조작', show: false},
   { url: '/react-outside/effect/effect-basic', name: 'side Effect', show: false},
   { url: '/react-outside/effect/no-need-effect', name: 'Effect 제거', show: false},
   { url: '/react-outside/effect/effect-lifecycle', name: 'effect lifecycle', show: false},
   { url: '/react-outside/effect/event-from-effect', name: 'useEffectEvent', show: false},
   { url: '/react-outside/effect/custom-hook', name: 'custom hook', show: false},
   { url: '/javascript/js/js-basic', name: 'basic', show: false},
   { url: '/javascript/js/js-array-if-loop', name: 'array/if/loop', show: false},
   { url: '/javascript/js/function', name: 'function', show: false},
   { url: '/javascript/js/event-handling', name: 'event handling', show: false},
   { url: '/javascript/js/blob', name: 'blob', show: false},
   { url: '/javascript/object/object-basic', name: 'object basic', show: false},
   { url: '/javascript/object/object-prototype', name: 'object proto', show: false},
   { url: '/javascript/object/inheritance', name: 'inheritance', show: false},
   { url: '/javascript/object/json', name: 'json', show: false},
   { url: '/javascript/async/async-basic', name: 'async ?', show: false},
   { url: '/javascript/async/async-event-handler', name: 'Async', show: false},
   { url: '/javascript/async/promises', name: 'Promises', show: false},
   { url: '/javascript/async/promises-multiple', name: 'promiseMulti', show: false},
   { url: '/javascript/async/promises-custom', name: 'CustomPromise', show: false},
   { url: '/javascript/async/promises-api', name: 'PromiseApi', show: false},
   { url: '/javascript/async/js-worker', name: 'JsWorker', show: false},
];

export {mainNav, subs, links}