const mainNav = [
   { url: '/react-inside', name: 'inside react'},
   { url: '/react-outside', name: 'outside react'},
   { url: '/html-css', name: 'html css'},
   { url: '/javascript', name: 'javascript' },
];

const subs = [
   { url: '/react-inside/rendering', name: 'jsx markup'},
   { url: '/react-inside/event', name: 'react events'},
   { url: '/react-inside/state', name: 'State Management'},
   { url: '/react-outside/ref-effect', name: 'ref and effect'},
   { url: '/html-css/html-basic', name: 'html'},
   { url: '/html-css/css-tips', name: 'css tips'},
   { url: '/html-css/css-attribute', name: 'css attribute'},
   { url: '/html-css/form-basic', name: 'form basic'},
   { url: '/html-css/form-types', name: 'form 종류'},
   { url: '/html-css/input-types', name: 'input 종류'},
   { url: '/javascript/js', name: 'js basic'},
   { url: '/javascript/object', name: 'js object'},
   { url: '/javascript/async', name: 'js async'},
];
const links = [
   { url: '/react-inside/rendering/jsx-markup', name: 'jsx markup'},
   { url: '/react-inside/rendering/props-injection', name: 'props injection'},
   { url: '/react-inside/rendering/how-rendering', name: 'how to render'},
   { url: '/react-inside/rendering/ui-tree', name: 'ui tree'},
   { url: '/react-inside/event/event-handle', name: 'event handling'},
   { url: '/react-inside/event/handle-state', name: 'handling state'},
   { url: '/react-inside/event/rendering-commit', name: 'rendering commit'},
   { url: '/react-inside/event/object-state-update', name: 'object state update'},
   { url: '/react-inside/event/array-state-update', name: 'array state update'},
   { url: '/react-inside/state/handle-useState', name: 'handle input'},
   { url: '/react-inside/state/state-architecture', name: 'state 구조화'},
   { url: '/react-inside/state/state-hoisting', name: 'Component 간 state 공유'},
   { url: '/react-inside/state/state-reducer', name: 'state reducer'},
   { url: '/react-inside/state/context-prop-delivery', name: 'Context: prop delivery'},
   { url: '/react-inside/state/context-useReducer', name: 'Context, useReducer'},
   { url: '/react-outside/ref-effect/using-ref', name: 'ref로 값 참조'},
   { url: '/react-outside/ref-effect/DOM-by-ref', name: 'Ref로 DOM조작'},
   { url: '/react-outside/ref-effect/effect-basic', name: 'side Effect'},
   { url: '/javascript/js/js-basic', name: 'js basic'},
   { url: '/javascript/js/js-array-if-loop', name: 'array/if/loop'},
   { url: '/javascript/js/function', name: 'function'},
   { url: '/javascript/js/event-handling', name: 'event handling'},
   { url: '/javascript/js/blob', name: 'blob'},
   { url: '/javascript/object/object-basic', name: 'object basic'},
   { url: '/javascript/object/object-prototype', name: 'object prototype'},
   { url: '/javascript/object/inheritance', name: 'inheritance'},
   { url: '/javascript/object/json', name: 'json'},
   { url: '/javascript/async/async-basic', name: 'async basic'},
   { url: '/javascript/async/async-event-handler', name: 'async event handler'},
   { url: '/javascript/async/promises', name: 'promises ex'},
   { url: '/javascript/async/promises-multiple', name: 'promise multiple'},
   { url: '/javascript/async/promises-custom', name: 'custom promise'},
   { url: '/javascript/async/promises-api', name: 'promise api'},
   { url: '/javascript/async/js-worker', name: 'js worker'},
];

export {mainNav, subs, links}