const mainNav = [
   { url: '/react-inside', name: 'inside react', show: false},
   { url: '/react-outside', name: 'outside react', show: false},
   { url: '/html-css', name: 'HTML css', show: false},
   { url: '/javascript', name: 'JavaScript' , show: false},
];

const subs = [
   { url: '/react-inside/rendering', name: 'jsx markup', show: false},
   { url: '/react-inside/event', name: 'react events', show: false},
   { url: '/react-inside/state', name: 'State Management', show: false},
   { url: '/react-outside/ref', name: 'ref', show: false},
   { url: '/react-outside/effect', name: 'Effect', show: false},
   { url: '/html-css/html-basic', name: 'html', show: false},
   { url: '/html-css/css-tips', name: 'css tips', show: false},
   { url: '/html-css/css-attribute', name: 'css attribute', show: false},
   { url: '/html-css/form-basic', name: 'form basic', show: false},
   { url: '/html-css/form-types', name: 'form 종류', show: false},
   { url: '/html-css/input-types', name: 'input 종류', show: false},
   { url: '/javascript/js', name: 'basic', show: false},
   { url: '/javascript/object', name: 'object', show: false},
   { url: '/javascript/async', name: 'async', show: false},
];
const links = [
   { url: '/react-inside/rendering/jsx-markup', name: 'jsx markup', show: false},
   { url: '/react-inside/rendering/props-injection', name: 'props injection', show: false},
   { url: '/react-inside/rendering/how-rendering', name: 'how to render', show: false},
   { url: '/react-inside/event/event-handle', name: 'event handling', show: false},
   { url: '/react-inside/event/handle-state', name: 'handling state', show: false},
   { url: '/react-inside/event/rendering-commit', name: 'rendering commit', show: false},
   { url: '/react-inside/event/object-state-update', name: 'object state update', show: false},
   { url: '/react-inside/event/array-state-update', name: 'array state update', show: false},
   { url: '/react-inside/state/handle-useState', name: 'handle input', show: false},
   { url: '/react-inside/state/state-architecture', name: 'state 구조화', show: false},
   { url: '/react-inside/state/state-hoisting', name: 'Component 간 state 공유', show: false},
   { url: '/react-inside/state/state-reducer', name: 'state reducer', show: false},
   { url: '/react-inside/state/context-prop-delivery', name: 'Context: prop delivery', show: false},
   { url: '/react-inside/state/context-useReducer', name: 'Context, useReducer', show: false},
   { url: '/react-outside/ref/using-ref', name: 'ref로 값 참조', show: false},
   { url: '/react-outside/ref/DOM-by-ref', name: 'Ref로 DOM조작', show: false},
   { url: '/react-outside/effect/effect-basic', name: 'side Effect', show: false},
   { url: '/react-outside/effect/no-need-effect', name: '불필요 Effect 제거', show: false},
   { url: '/javascript/js/js-basic', name: 'basic', show: false},
   { url: '/javascript/js/js-array-if-loop', name: 'array/if/loop', show: false},
   { url: '/javascript/js/function', name: 'function', show: false},
   { url: '/javascript/js/event-handling', name: 'event handling', show: false},
   { url: '/javascript/js/blob', name: 'blob', show: false},
   { url: '/javascript/object/object-basic', name: 'object basic', show: false},
   { url: '/javascript/object/object-prototype', name: 'object prototype', show: false},
   { url: '/javascript/object/inheritance', name: 'inheritance', show: false},
   { url: '/javascript/object/json', name: 'json', show: false},
   { url: '/javascript/async/async-basic', name: 'async ?', show: false},
   { url: '/javascript/async/async-event-handler', name: 'async event handler', show: false},
   { url: '/javascript/async/promises', name: 'promises ex', show: false},
   { url: '/javascript/async/promises-multiple', name: 'promise multiple', show: false},
   { url: '/javascript/async/promises-custom', name: 'custom promise', show: false},
   { url: '/javascript/async/promises-api', name: 'promise api', show: false},
   { url: '/javascript/async/js-worker', name: 'js worker', show: false},
];

export {mainNav, subs, links}